# Generated by Django 5.0.4 on 2024-04-04 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=20)),
                ('weight_limit', models.FloatField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9\\-\\' ]+$", 'Only letters, numbers, hyphen, and apostrophe are allowed in the name.')])),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Only uppercase letters, numbers, and underscore are allowed in the code.')])),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
