# Generated by Django 5.0.4 on 2024-04-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='medication',
            field=models.ManyToManyField(blank=True, related_name='medication', to='drones.medication'),
        ),
    ]
